package com.aican.tlcanalyzer.ui.pages.image_analysis.intensity_plot

import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.padding
import androidx.compose.material3.Scaffold
import androidx.compose.runtime.Composable
import androidx.compose.runtime.collectAsState
import androidx.compose.runtime.getValue
import androidx.compose.ui.Modifier
import com.aican.tlcanalyzer.data.database.project.entities.ContourData
import com.aican.tlcanalyzer.domain.states.graph.IntensityDataState
import com.aican.tlcanalyzer.ui.components.topbar_navigation.CustomTopBar
import com.aican.tlcanalyzer.ui.pages.image_analysis.components.IntensityDataSection
import com.aican.tlcanalyzer.viewmodel.project.ImageAnalysisViewModel
import com.aican.tlcanalyzer.viewmodel.project.IntensityChartViewModel
import com.aican.tlcanalyzer.viewmodel.project.ProjectViewModel
import com.github.mikephil.charting.data.Entry

@Composable
fun IntensityPlotScreen(
    modifier: Modifier = Modifier,
    imageAnalysisViewModel: ImageAnalysisViewModel,
    intensityChartViewModel: IntensityChartViewModel,
    projectViewModel: ProjectViewModel,
) {

    val contourDataList by imageAnalysisViewModel.allAutoGeneratedSpotsData.collectAsState()
    val intensityDataState by imageAnalysisViewModel.intensityDataState.collectAsState()
    val lineChartData by intensityChartViewModel.lineChartDataList.collectAsState()
    val numberOfIntensityParts by projectViewModel.cachedIntensityParts.collectAsState()

    Scaffold(
        topBar = {
            CustomTopBar(
                title = "Intensity Plot",
                onBackClick = { /* Handle back navigation */ }
            )
        },
    ) { internalPadding ->
        Column(modifier = Modifier.fillMaxSize().padding(internalPadding)) {


            IntensityDataSection(
                parts = numberOfIntensityParts ?: 100,
                intensityDataState = intensityDataState, lineChartData = lineChartData,
                contourDataList = contourDataList
            )
        }
    }

}